services:
  prometheus:
    image: prom/prometheus:latest
    container_name: ${PROMETHEUS_CONTAINER_NAME}
    environment:
      - VIRTUAL_HOST=${PROMETHEUS_VIRTUAL_HOST}
      - VIRTUAL_PORT=${PROMETHEUS_VIRTUAL_PORT}
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    restart: unless-stopped
    networks:
      - my_proxy_network

  grafana:
    image: grafana/grafana:latest
    container_name: ${GRAFANA_CONTAINER_NAME}
    environment:
      - VIRTUAL_HOST=${GRAFANA_VIRTUAL_HOST}
      - VIRTUAL_PORT=${GRAFANA_VIRTUAL_PORT}
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    restart: unless-stopped
    networks:
      - my_proxy_network
  tempo:
    image: grafana/tempo:2.8.1
    container_name: ${TEMPO_CONTAINER_NAME}
    environment:
      - VIRTUAL_HOST=${TEMPO_VIRTUAL_HOST}
      - VIRTUAL_PORT=${TEMPO_VIRTUAL_PORT}
    volumes:
      - ./tempo:/etc/tempo
      - tempo_data:/var/lib/tempo
    user: root
    command: ["-config.file=/etc/tempo/tempo.yaml"]
    restart: unless-stopped
    networks:
      - my_proxy_network

networks:
  my_proxy_network:
    external: true

volumes:
  prometheus_data:
  grafana_data:
  tempo_data:
